// 用户信息部分
export const SET_USER_NAME = 'SET_USER_NAME'
export const SET_USRE_ID = 'SET_USER_ID'
export const SET_USER_AVATAR = 'SET_USER_AVATAR'
export const SET_USER_ROLE = 'SET_USER_ROLE'
export const SET_USER_REGIONID = 'SET_USER_REGIONID'
export const SET_USER_PERIODID = 'SET_USER_PERIODID'
export const SET_USER_SUBJECTID = 'SET_USER_SUBJECTID'

// 界面部分
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const SET_SGROPTIONS = 'SET_SGROPTIONS'
export const UPDATE_MENULIST = 'UPDATE_MENULIST'
export const SET_ROUTES = 'SET_ROUTES'
