// 用户信息部分
export const SET_USER_NAME = 'SET_USER_NAME'
export const SET_USRE_ID = 'SET_USER_ID'
export const SET_USER_AVATAR = 'SET_USER_AVATAR'
export const SET_USER_ROLE = 'SET_USER_ROLE'
export const SET_USER_REGIONID = 'SET_USER_REGIONID'
export const SET_USER_PERIODID = 'SET_USER_PERIODID'
export const SET_USER_SUBJECTID = 'SET_USER_SUBJECTID'

// 界面部分
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const SET_SGROPTIONS = 'SET_SGROPTIONS'
export const UPDATE_MENULIST = 'UPDATE_MENULIST'
export const SET_ROUTES = 'SET_ROUTES'

// 基础信息
export const SET_BASEDATA = 'SET_BASEDATA'
export const SET_REDION_OPTIONS = 'SET_REDION_OPTIONS'
export const SET_PERIOD_OPTIONS = 'SET_PERIOD_OPTIONS'
export const SET_SUBJECT_OPTIONS = 'SET_SUBJECT_OPTIONS'
// export const SET_GRADE_OPTIONS = 'SET_GRADE_OPTIONS'
// export const SET_TBTYPE_OPTIONS = 'SET_TBTYPE_OPTIONS'
// export const SET_SEASON_OPTIONS = 'SET_SEASON_OPTIONS'
// export const SET_PRODUCT_OPTIONS = 'SET_PRODUCT_OPTIONS'
// export const SET_ITEMTYPE_OPTIONS = 'SET_ITEMTYPE_OPTIONS'
// export const SET_PAPERTYPE_OPTIONS = 'SET_PAPERTYPE_OPTIONS'
// export const SET_YEAR_OPTIONS = 'SET_YEAR_OPTIONS'
// export const SET_LEVEL_OPTIONS = 'SET_LEVEL_OPTIONS'
// export const SET_DEPARTMENT_OPTIONS = 'SET_DEPARTMENT_OPTIONS'

export const SET_TEACHER_STEPS = 'SET_TEACHER_STEPS'
